server:
  port: 8082

spring:
  application:
    name: notification-service

management:
  tracing:
    sampling:
      probability: 1.0
  #  metrics:
#    export:
#      prometheus:
#        enabled: true
  endpoints:
    web:
      exposure:
        include: health #prometheus,metrics,health
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 2s

