global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
#  - job_name: "order-service-app"
#    metrics_path: /actuator/prometheus
#    static_configs:
#      - targets: ['host.docker.internal:8080']
  - job_name: "otel-collector"
    static_configs:
      - targets: ['otel-collector:8889']

